#!/usr/bin/env bash
#Copyright 2016 Confluent Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o nounset \
    -o errexit \
    -o verbose \
    -o xtrace


# Set environment values if they exist as arguments
if [ $# -ne 0 ]; then
  echo "===> Overriding env params with args ..."
    for var in "$@"
    do
      export "$var"
    done
fi

echo "===> ENV Variables ..."
env | sort

echo "===> User"
id

echo "===> Configuring ..."
/etc/confluent/docker/configure

echo "===> Running preflight checks ... "
/etc/confluent/docker/ensure

echo "===> Launching ... "
exec /etc/confluent/docker/launch

echo "===> Creating topics ... "
kafka-topics --zookeeper smartaqnet-0-node0:22181 --create --topic Datastreams --replication-factor 3 --partitions 1 --config retention.ms=-1
kafka-topics --zookeeper smartaqnet-0-node0:22181 --create --topic MultiDatastreams --replication-factor 3 --partitions 1 --config retention.ms=-1
kafka-topics --zookeeper smartaqnet-0-node0:22181 --create --topic FeaturesOfInterest --replication-factor 3 --partitions 1 --config retention.ms=-1
kafka-topics --zookeeper smartaqnet-0-node0:22181 --create --topic HistoricalLocations --replication-factor 3 --partitions 1 --config retention.ms=-1
kafka-topics --zookeeper smartaqnet-0-node0:22181 --create --topic Locations --replication-factor 3 --partitions 1 --config retention.ms=-1
kafka-topics --zookeeper smartaqnet-0-node0:22181 --create --topic Observations --replication-factor 3 --partitions 1 --config retention.ms=-1
kafka-topics --zookeeper smartaqnet-0-node0:22181 --create --topic ObservedProperties --replication-factor 3 --partitions 1 --config retention.ms=-1
kafka-topics --zookeeper smartaqnet-0-node0:22181 --create --topic Sensors --replication-factor 3 --partitions 1 --config retention.ms=-1
kafka-topics --zookeeper smartaqnet-0-node0:22181 --create --topic Things --replication-factor 3 --partitions 1 --config retention.ms=-1

