FROM grafana/grafana:latest
USER root
ADD linksmart-sensorthings-datasource  /var/lib/grafana/plugins/linksmart-sensorthings-datasource
#RUN git clone https://code.linksmart.eu/scm/gst/grafana-sensorthings-datasource.git /var/lib/grafana/plugins/grafana-sensorthings-datasource 
USER grafana
